# Generated by Django 2.2 on 2019-11-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20191109_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoritem',
            name='available_on',
            field=models.DateTimeField(),
        ),
    ]
